// build-sea.ts -- packages ts0 as prebuilt, self-contained single-executable
// (SEA) binaries for publishing to buildhost (dl.pazer.build/ts0).
//
// For each target platform it:
//   1. Bundles src/sea/main.ts (prelude + CLI) to ONE CommonJS file with
//      esbuild. `esbuild` itself stays external (loaded at runtime from the
//      extracted cache via globalThis.__ts0SeaRequire) and `import.meta.url`
//      is rewritten to globalThis.__ts0SeaImportMetaUrl (set by the prelude),
//      so the bundle's module resolution can be pointed at the cache dir.
//   2. Stages the runtime assets: a pruned `typescript` package (bin/tsc +
//      lib/tsc.js + lib/_tsc.js + lib/lib.*.d.ts), the `esbuild` JS package
//      (package.json + lib/main.js), the platform's @esbuild native binary
//      (downloaded from the npm registry and verified against the
//      package-lock integrity hash), and src/runtime/fetch-interceptor.js.
//   3. Generates the SEA blob (bundle + assets + manifest) with the pinned
//      Node version and injects it into that platform's official Node binary
//      (downloaded from nodejs.org and verified against SHASUMS256.txt) via
//      postject.
//
// Output: build-sea/out/ts0_<os>_<arch>[.exe]
//
// The darwin binaries come out of this script UNSIGNED (injection invalidates
// the Apple signature and this script runs on Linux); CI's macOS smoke job
// ad-hoc re-signs them with the real `codesign` before they are verified and
// published. Host requirement: linux/amd64 (the blob is generated by running
// the downloaded linux-x64 Node of the SAME pinned version, so blob and
// runtime can never drift).
//
// Usage: node --experimental-strip-types scripts/build-sea.ts [--targets linux/amd64,...]

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
	chmodSync,
	copyFileSync,
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";

// The exact Node runtime embedded in every binary. Bump deliberately; the
// build id (and therefore the cache dir) changes with it.
const NODE_VERSION = "22.22.2";

interface Target {
	os: "linux" | "darwin" | "windows"; // buildhost os name
	arch: "amd64" | "arm64"; // buildhost arch name
	nodePlatform: string; // nodejs.org dist archive suffix
	nodeArchive: "tar.xz" | "zip";
	esbuildPkg: string; // @esbuild/<name>
	esbuildBin: string; // binary subpath inside the package
	exeSuffix: string;
}

const TARGETS: Target[] = [
	{ os: "linux", arch: "amd64", nodePlatform: "linux-x64", nodeArchive: "tar.xz", esbuildPkg: "@esbuild/linux-x64", esbuildBin: "bin/esbuild", exeSuffix: "" },
	{ os: "linux", arch: "arm64", nodePlatform: "linux-arm64", nodeArchive: "tar.xz", esbuildPkg: "@esbuild/linux-arm64", esbuildBin: "bin/esbuild", exeSuffix: "" },
	{ os: "darwin", arch: "amd64", nodePlatform: "darwin-x64", nodeArchive: "tar.xz", esbuildPkg: "@esbuild/darwin-x64", esbuildBin: "bin/esbuild", exeSuffix: "" },
	{ os: "darwin", arch: "arm64", nodePlatform: "darwin-arm64", nodeArchive: "tar.xz", esbuildPkg: "@esbuild/darwin-arm64", esbuildBin: "bin/esbuild", exeSuffix: "" },
	{ os: "windows", arch: "amd64", nodePlatform: "win-x64", nodeArchive: "zip", esbuildPkg: "@esbuild/win32-x64", esbuildBin: "esbuild.exe", exeSuffix: ".exe" },
];

const repoRoot = resolve(dirname(new URL(import.meta.url).pathname), "..");
const buildDir = join(repoRoot, "build-sea");
const downloadDir = join(buildDir, "downloads");
const outDir = join(buildDir, "out");
const requireLocal = createRequire(join(repoRoot, "package.json"));

interface ManifestFile {
	key: string;
	executable?: boolean;
}

function sh(cmd: string, args: string[], opts: { cwd?: string } = {}): void {
	execFileSync(cmd, args, { stdio: ["ignore", "inherit", "inherit"], cwd: opts.cwd });
}

function sha256(buf: Buffer): string {
	return createHash("sha256").update(buf).digest("hex");
}

function download(url: string, dest: string): void {
	if (existsSync(dest)) return;
	console.log(`  downloading ${url}`);
	mkdirSync(dirname(dest), { recursive: true });
	const tmp = `${dest}.part`;
	sh("curl", ["-fSL", "--retry", "3", "-o", tmp, url]);
	copyFileSync(tmp, dest);
	rmSync(tmp);
}

// verifyNodeArchive checks a downloaded nodejs.org archive against the
// release's SHASUMS256.txt (also downloaded and cached).
function verifyNodeArchive(archivePath: string, fileName: string): void {
	const shasums = join(downloadDir, `SHASUMS256-${NODE_VERSION}.txt`);
	download(`https://nodejs.org/dist/v${NODE_VERSION}/SHASUMS256.txt`, shasums);
	const line = readFileSync(shasums, "utf-8")
		.split("\n")
		.find((l) => l.endsWith(`  ${fileName}`));
	if (!line) throw new Error(`no SHASUMS256 entry for ${fileName}`);
	const expected = line.split(/\s+/)[0];
	const actual = sha256(readFileSync(archivePath));
	if (actual !== expected) {
		rmSync(archivePath);
		throw new Error(`sha256 mismatch for ${fileName}: expected ${expected}, got ${actual}`);
	}
}

// verifyNpmTarball checks a registry tarball against the sha512 integrity
// recorded in package-lock.json for that package -- the same pin `npm ci`
// enforces for the host platform's copy.
function verifyNpmTarball(tarPath: string, pkgName: string): void {
	const lock = JSON.parse(readFileSync(join(repoRoot, "package-lock.json"), "utf-8")) as {
		packages: Record<string, { integrity?: string }>;
	};
	const entry = lock.packages[`node_modules/${pkgName}`];
	if (!entry?.integrity?.startsWith("sha512-")) {
		throw new Error(`no sha512 integrity for ${pkgName} in package-lock.json`);
	}
	const expected = entry.integrity.slice("sha512-".length);
	const actual = createHash("sha512").update(readFileSync(tarPath)).digest("base64");
	if (actual !== expected) {
		rmSync(tarPath);
		throw new Error(`integrity mismatch for ${pkgName} tarball`);
	}
}

function installedVersion(pkg: string): string {
	return (JSON.parse(readFileSync(requireLocal.resolve(`${pkg}/package.json`), "utf-8")) as { version: string }).version;
}

// bundle produces the single CommonJS file embedded as the SEA main script.
// It is platform-independent: everything platform-specific lives in the
// per-target assets.
async function bundle(): Promise<string> {
	const esbuild = requireLocal("esbuild") as typeof import("esbuild");
	const outfile = join(buildDir, "ts0-sea.cjs");
	await esbuild.build({
		entryPoints: [join(repoRoot, "src/sea/main.ts")],
		bundle: true,
		platform: "node",
		format: "cjs",
		target: "node22",
		outfile,
		sourcemap: false,
		logLevel: "warning",
		// The SEA main script's ambient require() only loads builtins;
		// import.meta.url does not exist in CJS. Both are redirected to
		// globals the prelude sets up before any consumer evaluates.
		define: { "import.meta.url": "globalThis.__ts0SeaImportMetaUrl" },
		plugins: [
			{
				name: "sea-external-esbuild",
				setup(b) {
					b.onResolve({ filter: /^esbuild$/ }, (args) => ({ path: args.path, namespace: "sea-external" }));
					b.onLoad({ filter: /.*/, namespace: "sea-external" }, (args) => ({
						contents: `module.exports = globalThis.__ts0SeaRequire(${JSON.stringify(args.path)});`,
						loader: "js",
					}));
				},
			},
		],
	});
	return outfile;
}

// stageCommon copies the platform-independent assets (pruned typescript,
// esbuild JS package, interceptor template) into a staging tree mirroring
// the cache layout. Returns the manifest entries.
function stageCommon(stage: string): ManifestFile[] {
	const files: ManifestFile[] = [];
	const put = (key: string, from: string, executable = false): void => {
		const dest = join(stage, ...key.split("/"));
		mkdirSync(dirname(dest), { recursive: true });
		copyFileSync(from, dest);
		files.push(executable ? { key, executable } : { key });
	};

	put("src/runtime/fetch-interceptor.js", join(repoRoot, "src/runtime/fetch-interceptor.js"));

	// typescript, pruned to what `tsc --project` needs at runtime: the CLI
	// entry chain and the bundled standard libraries. (typescript.js, the
	// language service, and the locale directories are never loaded.)
	const tsDir = dirname(requireLocal.resolve("typescript/package.json"));
	for (const key of ["package.json", "bin/tsc", "lib/tsc.js", "lib/_tsc.js"]) {
		put(`node_modules/typescript/${key}`, join(tsDir, key));
	}
	const libFiles = readdirSync(join(tsDir, "lib")).filter((f) => f.startsWith("lib.") && f.endsWith(".d.ts"));
	if (libFiles.length === 0) throw new Error("no lib.*.d.ts found in typescript/lib");
	for (const f of libFiles) put(`node_modules/typescript/lib/${f}`, join(tsDir, "lib", f));

	// esbuild's JS package (the API); the native binary is per-target.
	const esbuildDir = dirname(requireLocal.resolve("esbuild/package.json"));
	put("node_modules/esbuild/package.json", join(esbuildDir, "package.json"));
	put("node_modules/esbuild/lib/main.js", join(esbuildDir, "lib", "main.js"));

	return files;
}

// stageEsbuildNative downloads the target's @esbuild native package from the
// npm registry (verified against package-lock) and stages package.json plus
// the binary. Returns the manifest entries.
function stageEsbuildNative(stage: string, target: Target, esbuildVersion: string): ManifestFile[] {
	const bare = target.esbuildPkg.split("/")[1];
	const tarPath = join(downloadDir, `${bare}-${esbuildVersion}.tgz`);
	download(`https://registry.npmjs.org/${target.esbuildPkg}/-/${bare}-${esbuildVersion}.tgz`, tarPath);
	verifyNpmTarball(tarPath, target.esbuildPkg);

	const extractDir = join(downloadDir, `esbuild-${bare}-${esbuildVersion}`);
	if (!existsSync(join(extractDir, "package", "package.json"))) {
		mkdirSync(extractDir, { recursive: true });
		sh("tar", ["-xzf", tarPath, "-C", extractDir]);
	}

	const files: ManifestFile[] = [];
	for (const [key, executable] of [
		[`node_modules/${target.esbuildPkg}/package.json`, false],
		[`node_modules/${target.esbuildPkg}/${target.esbuildBin}`, true],
	] as const) {
		// Strip the node_modules/@esbuild/<name>/ prefix (three segments --
		// the scope and name are separate) to get the in-package path.
		const from = join(extractDir, "package", ...key.split("/").slice(3));
		const dest = join(stage, ...key.split("/"));
		mkdirSync(dirname(dest), { recursive: true });
		copyFileSync(from, dest);
		files.push(executable ? { key, executable } : { key });
	}
	return files;
}

// nodeBinary downloads and extracts the official Node binary for a target.
function nodeBinary(target: Target): string {
	const base = `node-v${NODE_VERSION}-${target.nodePlatform}`;
	const archive = `${base}.${target.nodeArchive}`;
	const archivePath = join(downloadDir, archive);
	download(`https://nodejs.org/dist/v${NODE_VERSION}/${archive}`, archivePath);
	verifyNodeArchive(archivePath, archive);

	const binPath =
		target.nodeArchive === "zip" ? join(downloadDir, base, "node.exe") : join(downloadDir, base, "bin", "node");
	if (!existsSync(binPath)) {
		if (target.nodeArchive === "zip") {
			sh("unzip", ["-oq", archivePath, `${base}/node.exe`, "-d", downloadDir]);
		} else {
			sh("tar", ["-xJf", archivePath, "-C", downloadDir, `${base}/bin/node`]);
		}
	}
	return binPath;
}

async function buildTarget(target: Target, bundlePath: string, commonStage: string, commonFiles: ManifestFile[]): Promise<string> {
	const name = `${target.os}/${target.arch}`;
	console.log(`packaging ${name}`);
	const esbuildVersion = installedVersion("esbuild");
	const stage = join(buildDir, `stage-${target.os}-${target.arch}`);
	rmSync(stage, { recursive: true, force: true });
	mkdirSync(stage, { recursive: true });

	const nativeFiles = stageEsbuildNative(stage, target, esbuildVersion);
	const files = [...commonFiles, ...nativeFiles];

	// The build id covers everything that affects runtime behavior: the
	// bundle, every asset byte, the embedded Node version, and the target.
	// It names the extraction cache dir, so any change extracts fresh.
	const id = createHash("sha256");
	id.update(`node-v${NODE_VERSION}\0${target.os}/${target.arch}\0`);
	id.update(readFileSync(bundlePath));
	const assetPath = (key: string): string =>
		existsSync(join(commonStage, ...key.split("/"))) ? join(commonStage, ...key.split("/")) : join(stage, ...key.split("/"));
	for (const f of files.slice().sort((a, b) => a.key.localeCompare(b.key))) {
		id.update(`\0${f.key}\0${f.executable ? "x" : "-"}\0`);
		id.update(readFileSync(assetPath(f.key)));
	}
	const buildId = id.digest("hex").slice(0, 16);

	const manifest = { buildId, files };
	const manifestPath = join(stage, "manifest.json");
	writeFileSync(manifestPath, JSON.stringify(manifest, null, "\t"));

	const assets: Record<string, string> = { "manifest.json": manifestPath };
	for (const f of files) assets[f.key] = assetPath(f.key);

	const seaConfigPath = join(stage, "sea-config.json");
	const blobPath = join(stage, "ts0-sea.blob");
	writeFileSync(
		seaConfigPath,
		JSON.stringify({ main: bundlePath, output: blobPath, disableExperimentalSEAWarning: true, assets }, null, "\t"),
	);

	// Generate the blob with the SAME pinned Node version that will run it
	// (the downloaded linux-x64 binary), never the host's node -- the blob
	// format is not guaranteed stable across versions.
	const blobNode = nodeBinary(TARGETS.find((t) => t.nodePlatform === "linux-x64")!);
	sh(blobNode, ["--experimental-sea-config", seaConfigPath]);

	// Copy the target's official Node binary and inject the blob.
	mkdirSync(outDir, { recursive: true });
	const outPath = join(outDir, `ts0_${target.os}_${target.arch}${target.exeSuffix}`);
	rmSync(outPath, { force: true });
	copyFileSync(nodeBinary(target), outPath);
	const { inject } = requireLocal("postject") as {
		inject: (file: string, resource: string, data: Buffer, opts?: { sentinelFuse?: string; machoSegmentName?: string }) => Promise<void>;
	};
	await inject(outPath, "NODE_SEA_BLOB", readFileSync(blobPath), {
		sentinelFuse: "NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2",
		...(target.os === "darwin" ? { machoSegmentName: "NODE_SEA" } : {}),
	});
	if (target.os !== "windows") chmodSync(outPath, 0o755);
	console.log(`  -> ${outPath} (build id ${buildId})`);
	return outPath;
}

async function main(): Promise<void> {
	if (process.platform !== "linux" || process.arch !== "x64") {
		throw new Error("build-sea.ts must run on linux/amd64 (the SEA blob is generated with the pinned linux-x64 Node)");
	}
	const targetsArg = process.argv.find((a) => a.startsWith("--targets="))?.slice("--targets=".length);
	const wanted = targetsArg ? targetsArg.split(",") : TARGETS.map((t) => `${t.os}/${t.arch}`);
	const targets = wanted.map((w) => {
		const t = TARGETS.find((t) => `${t.os}/${t.arch}` === w.trim());
		if (!t) throw new Error(`unknown target: ${w} (known: ${TARGETS.map((t) => `${t.os}/${t.arch}`).join(", ")})`);
		return t;
	});

	mkdirSync(downloadDir, { recursive: true });
	console.log(`bundling SEA main (node v${NODE_VERSION}, typescript ${installedVersion("typescript")}, esbuild ${installedVersion("esbuild")})`);
	const bundlePath = await bundle();

	const commonStage = join(buildDir, "stage-common");
	rmSync(commonStage, { recursive: true, force: true });
	mkdirSync(commonStage, { recursive: true });
	const commonFiles = stageCommon(commonStage);

	for (const target of targets) {
		await buildTarget(target, bundlePath, commonStage, commonFiles);
	}
}

main().catch((err: unknown) => {
	console.error(err);
	process.exit(1);
});
